var obj = JSON.parse($response.body);

obj =

{
  "data": {
    "login_ocr_balance": "4",
    "fax_balance": "0",
    "removead": "0",
    "points": "9999999999",
    "server_time": "1665706765",
    "balance_demoire": 1000,
    "CamScanner_Erase": 1000,
    "watchad_vip_chance_total": "3",
    "watchad_vip_chance": "3",
    "trans_balance": "2",
    "upload_pdf_balance": "5",
    "patting_balance": "3",
    "no_login_ocr_balance": "2",
    "points_exchange_cfgrs": {
      "CamScanner_CloudCap_1G": 1000,
      "CamScanner_CertMode": 200,
      "CamScanner_Pdf2excel": 500,
      "CamScanner_Profile_Card_Format": 1000,
      "CamScanner_Translation": 50,
      "CamScanner_Excel": 500,
      "CamScanner_Watermarks": 50,
      "CamScanner_CloudOCR": 50,
      "CamScanner_AlbumImport": 300,
      "CamScanner_ID_Card_Credit": 500,
      "CamScanner_ID_Card_Authenticity": 500,
      "CamScanner_Pdf2ppt": 500,
      "CamScanner_Sign": 500,
      "CamScanner_Pdfword": 500
    },
    "dir": {
      "edu_total_num": 1000,
      "vip_layer_num": 6,
      "vip_total_num": 5000,
      "normal_vip_total_num": 10,
      "normal_vip_layer_num": 6,
      "user_layer_num": 4,
      "user_total_num": 1000,
      "license_total_num": 1000,
      "license_layer_num": 4,
      "single_layer_num": 3,
      "advanced_folder_layer": 6,
      "advanced_folder_num": 1000,
      "new_layer_num": 4,
      "total_num": 8,
      "edu_layer_num": 6
    },
    "watermarks_balance": 100000,
    "pdfword_balance": "0",
    "ocr_balance": 200,
    "excel_balance": "1",
    "bookmode_balance": 20,
    "vip_imagerestore_balance": 1000,
    "imagerestore_balance": 8,
    "used_points": "0",
    "CamScanner_RoadMap": "0",
    "greetcard_list": {
      "CamScanner_NONVIP_PayGreetCard_3": "0",
      "greeting_card_1": "0",
      "greeting_card_2": "0",
      "greeting_card_3": "0",
      "greeting_card_4": "0",
      "greeting_card_5": "0",
      "greeting_card_6": "0",
      "greeting_card_9": "0",
      "greeting_card_10": "0",
      "greeting_card_11": "0",
      "CamScanner_PayGreetCard_1": "0",
      "CamScanner_PayGreetCard_2": "0",
      "CamScanner_PayGreetCard_3": "0",
      "CamScanner_PayGreetCard_4": "0",
      "CamScanner_PayGreetCard_5": "0",
      "CamScanner_PayGreetCard_6": "0",
      "CamScanner_NONVIP_PayGreetCard_1": "0",
      "CamScanner_NONVIP_PayGreetCard_2": "0"
    },
    "cert_mode_balance": 0,
    "balance_recolor": 8,
    "vip_balance_recolor": 1000,
    "immt_expy_points": "0"
  },
  "ret": "0"
}
$done({body: JSON.stringify(obj)});