var obj = JSON.parse($response.body);

obj =

{
  "ret": "0",
  "data": {
    "no_login_ocr_balance": "2",
    "cert_mode_balance": 0,
    "imagerestore_balance": 1000,
    "used_points": "0",
    "psnl_vip_property": {
      "in_trial": 0,
      "group1_paid": 1,
      "group2_paid": 1,
      "ys_first_pay": 0,
      "renew_type": "year",
      "inherited_flag": 0,
      "ms_first_pay": 0,
      "vip_type": "vip",
      "grade": 1,
      "initial_tm": "1665715190",
      "renew_method": "appstore",
      "last_payment_method": "appstore",
      "auto_renewal": true,
      "nxt_renew_tm": "9915126887",
      "expiry": 9915126887,
      "svip": 1,
      "pc_vip": 1,
      "product_id": "com.intsig.camscanner.premiums.5year",
      "members_page": 1,
      "level_info": {
        "level": 1,
        "days": 4,
        "end_days": 30
      },
      "pending": 0
    },
    "greetcard_list": {
      "greeting_card_2": "0",
      "greeting_card_3": "0",
      "greeting_card_4": "0",
      "greeting_card_5": "0",
      "greeting_card_6": "0",
      "greeting_card_9": "0",
      "greeting_card_10": "0",
      "greeting_card_11": "0",
      "CamScanner_PayGreetCard_1": "0",
      "CamScanner_PayGreetCard_2": "0",
      "CamScanner_PayGreetCard_3": "0",
      "CamScanner_PayGreetCard_4": "0",
      "CamScanner_PayGreetCard_5": "0",
      "CamScanner_PayGreetCard_6": "0",
      "CamScanner_NONVIP_PayGreetCard_1": "0",
      "CamScanner_NONVIP_PayGreetCard_2": "0",
      "CamScanner_NONVIP_PayGreetCard_3": "0",
      "greeting_card_1": "0"
    },
    "server_time": "1665715391",
    "balance_demoire": 1000,
    "vip_imagerestore_balance": 1000,
    "CamScanner_Erase": 1000,
    "CamScanner_RoadMap": "100000",
    "fax_balance": "50",
    "removead": "0",
    "points": "999999",
    "balance_recolor": 1000,
    "vip_balance_recolor": 1000,
    "ocr_balance": 1100,
    "points_exchange_cfgrs": {
      "CamScanner_CloudOCR": 50,
      "CamScanner_Profile_Card_Format": 1000,
      "CamScanner_CloudCap_1G": 1000,
      "CamScanner_Excel": 500,
      "CamScanner_Watermarks": 50,
      "CamScanner_Pdfword": 500,
      "CamScanner_Pdf2excel": 500,
      "CamScanner_Pdf2ppt": 500,
      "CamScanner_ID_Card_Authenticity": 500,
      "CamScanner_Translation": 50,
      "CamScanner_ID_Card_Credit": 500,
      "CamScanner_AlbumImport": 300,
      "CamScanner_CertMode": 200,
      "CamScanner_Sign": 500
    },
    "dir": {
      "single_layer_num": 3,
      "user_total_num": 5000,
      "advanced_folder_num": 1000,
      "new_layer_num": 4,
      "total_num": 8,
      "edu_layer_num": 6,
      "edu_total_num": 1000,
      "vip_layer_num": 6,
      "vip_total_num": 5000,
      "normal_vip_total_num": 10,
      "normal_vip_layer_num": 6,
      "advanced_folder_layer": 6,
      "user_layer_num": 6,
      "license_total_num": 1000,
      "license_layer_num": 4
    },
    "watchad_vip_chance": "3",
    "trans_balance": "1000",
    "upload_pdf_balance": "100000",
    "patting_balance": "100000",
    "bookmode_balance": 100010,
    "pdfword_balance": "100000",
    "watchad_vip_chance_total": "3",
    "watermarks_balance": 100000,
    "immt_expy_points": "0",
    "excel_balance": "500",
    "login_ocr_balance": "4"
  }
}
$done({body: JSON.stringify(obj)});