var obj = JSON.parse($response.body);
obj= 
[{
  "voucher": null,
  "orders": null,
  "upgrades": null,
  "offerUpgrades": null,
  "regrets": null,
  "customer": {
    "id": 43714,
    "digitalId": 6781632,
    "analogicalId": null,
    "crmId": "c5a5ce30-3c8c-ea11-a811-000d3a252d60",
    "active": true,
    "legalCondition": null,
    "owner": null,
    "email": "fedemf35@gmail.com",
    "name": ""
  },
  "billingCrmId": null,
  "wpCrmId": null,
  "geoCrmId": null,
  "pmuid": "mzEulZmZWui4N8-J_aS2qne8tLNhsH9y",
  "currentStatus": "canceled",
  "currentSubStatus": "payment_error",
  "renewalActionDate": null,
  "conversionActionDate": null,
  "endDate": "2021-05-08 08:19:06",
  "firstSubscription": null,
  "order": null,
  "id": 49908,
  "offer": {
    "id": 41,
    "description": "Acceso Anual desde App",
    "duration": "+1 year",
    "endDate": "",
    "name": "El Mundo Premium APP Anual",
    "permanency": null,
    "totalAmount": 69,
    "renewable": true,
    "startDate": "",
    "items": [{
      "id": 68,
      "type": "digital_access",
      "quantity": 1,
      "name": "El Mundo Premium",
      "productId": 5,
      "biller": "UESA",
      "sapId": "953",
      "pianoId": "TMER4731MGQ9",
      "analogicProductId": null,
      "portal": 8
    }],
    "tags": "PREMIUM,CAPTACION,APP,RETENCION",
    "renewalsLimit": null,
    "analogicOfferId": null,
    "analogicOfferGroupId": null,
    "categories": []
  },
  "booking": null,
  "paymentType": "apple",
  "permanencyDate": "2020-05-03 08:19:06",
  "startDate": "2020-05-02 08:19:06",
  "canceledDate": "2021-05-07 04:03:40",
  "successRenewals": null,
  "totalAmount": 90,
  "conversionDate": null,
  "conversionOffer": null,
  "cancellable": false,
  "paper": false,
  "reactivable": false,
  "isUndoCancelable": false,
  "totalAmountSubscription": 0,
  "isQr": null,
  "portal": 8,
  "giftCode": null,
  "payment3DSecure": null
}, {
  "voucher": null,
  "orders": null,
  "upgrades": null,
  "offerUpgrades": null,
  "regrets": null,
  "customer": {
    "id": 43714,
    "digitalId": 6781632,
    "analogicalId": null,
    "crmId": "c5a5ce30-3c8c-ea11-a811-000d3a252d60",
    "active": true,
    "legalCondition": null,
    "owner": null,
    "email": "fedemf35@gmail.com",
    "name": ""
  },
  "billingCrmId": null,
  "wpCrmId": null,
  "geoCrmId": null,
  "pmuid": "mzEulZmZWui4N8-J_aS2qne8tLNhsH9y",
  "currentStatus": "renewal_pending",
  "currentSubStatus": null,
  "renewalActionDate": "2025-09-03 04:00:00",
  "conversionActionDate": null,
  "endDate": "2025-09-04 05:23:13",
  "firstSubscription": null,
  "order": null,
  "id": 553691,
  "offer": {
    "id": 42,
    "description": "Acceso Mensual desde App",
    "duration": "+1 month",
    "endDate": "",
    "name": "El Mundo Premium APP Mensual",
    "permanency": null,
    "totalAmount": 7.99,
    "renewable": true,
    "startDate": "",
    "items": [{
      "id": 69,
      "type": "digital_access",
      "quantity": 1,
      "name": "El Mundo Premium",
      "productId": 5,
      "biller": "UESA",
      "sapId": "953",
      "pianoId": "TM3HIW51TJI7",
      "analogicProductId": null,
      "portal": 8
    }],
    "tags": "PREMIUM,CAPTACION,APP",
    "renewalsLimit": null,
    "analogicOfferId": null,
    "analogicOfferGroupId": null,
    "categories": []
  },
  "booking": null,
  "paymentType": "apple",
  "permanencyDate": "2022-07-31 05:23:13",
  "startDate": "2022-07-30 05:23:13",
  "canceledDate": null,
  "successRenewals": null,
  "totalAmount": 7.99,
  "conversionDate": null,
  "conversionOffer": null,
  "cancellable": false,
  "paper": false,
  "reactivable": false,
  "isUndoCancelable": false,
  "totalAmountSubscription": 0,
  "isQr": null,
  "portal": 8,
  "giftCode": null,
  "payment3DSecure": null
}]
$done({body: JSON.stringify(obj)});