name: ddgksf2013-Cuttlefish-sync
on:
  schedule:
    - cron: '45 */24 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-ddgksf2013-Cuttlefish
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: sync ddgksf2013-Cuttlefish
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://codeberg.org/ddgksf2013/Cuttlefish.git"
          source_branch: "master"
          destination_branch: "ddgksf2013-Cuttlefish"
          github_token: ${{ secrets.PAT }}