name: githubdulong-Script-sync
on:
  schedule:
    - cron: '45 */24 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-githubdulong-Script
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: sync githubdulong-Script
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/githubdulong/Script.git"
          source_branch: "master"
          destination_branch: "githubdulong-Script"
          github_token: ${{ secrets.PAT }}