name: YAOJIO-myself-sync
on:
  schedule:
    - cron: '45 */24 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-YAOJIO-myself
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: sync YAOJIO-myself
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/YAOJIO/myself.git"
          source_branch: "master"
          destination_branch: "YAOJIO-myself"
          github_token: ${{ secrets.PAT }}